export const productReviews = {
  'insta-captions-5': [
    { name: 'Priya S.', rating: 5, comment: 'Loved the variety! My engagement doubled in a week. The hooks are so creative – I used one for a product launch and got 50+ clicks.' },
    { name: 'Rahul K.', rating: 4, comment: 'Great hooks – saved me hours of brainstorming. A few are a bit generic, but overall a solid pack for the price.' },
    { name: 'Ananya M.', rating: 5, comment: 'Worth every rupee. My posts are getting 3x more comments now. I’ve recommended it to all my friends who run small businesses.' },
    { name: 'Vikram J.', rating: 4, comment: 'Good mix of curiosity and CTA hooks. I used one for a lead magnet campaign and got a 15% conversion rate – pretty good.' },
    { name: 'Neha D.', rating: 5, comment: 'These prompts saved me from writer’s block! I now have a month of captions ready. The pack is easy to use and very practical.' },
    { name: 'Suresh G.', rating: 3, comment: 'Some hooks are good, but others feel overused. Still decent for the price – I’d recommend it to beginners.' },
    { name: 'Maya P.', rating: 4, comment: 'Great for beginners – easy to adapt. I’ve already used them for 5 posts and my audience seems to like them.' },
    { name: 'Arjun R.', rating: 5, comment: 'The captions are so creative – my audience actually started a conversation in the comments. I’m really impressed with the quality.' },
    { name: 'Kavya N.', rating: 3, comment: 'Not bad, but I expected more variety. Some hooks are too similar. It’s okay for the price, but I’d look for a larger pack next time.' },
    { name: 'Deepak S.', rating: 5, comment: 'Exactly what I needed – simple, effective, and affordable. Highly recommend to anyone struggling with caption ideas.' },
    { name: 'Sneha R.', rating: 4, comment: 'Works well for my niche (fitness). Would love a version with longer form hooks, but these are great for daily posts.' },
    { name: 'Ajay K.', rating: 5, comment: 'I’ve seen a 30% increase in likes since using these. The hooks are fresh and engaging – my followers are more interactive.' },
    { name: 'Ritu G.', rating: 4, comment: 'Good variety, but some hooks don’t fit my brand voice – still useful to tweak. I appreciate the editable TXT format.' },
    { name: 'Vivek P.', rating: 5, comment: 'Best ₹25 I’ve spent. The ROI is incredible – I’ve already used 3 of the hooks for my client work.' },
    { name: 'Ankit M.', rating: 3, comment: 'Pretty standard hooks – nothing groundbreaking, but okay for the price. I’ll probably try the larger pack next time.' },
    { name: 'Riya T.', rating: 5, comment: 'Finally, captions that actually work! My engagement story changed overnight. I’m so happy I bought this pack.' },
    { name: 'Karan S.', rating: 4, comment: 'Good start for a newbie like me. Thanks Vaultizen – I’ll definitely be buying more packs.' },
    { name: 'Meera J.', rating: 5, comment: 'Cannot recommend enough. My clients are thrilled with the content – I’ve used these hooks for 3 different brands.' },
    { name: 'Aditya R.', rating: 2, comment: 'Too generic for my taste. Only a couple were usable – I expected more creativity. Won’t buy again.' },
    { name: 'Nisha P.', rating: 5, comment: 'Incredible value. I’ve already used three of the hooks and they’re gold – my post got 200+ likes on the first try.' },
    { name: 'Rohit G.', rating: 4, comment: 'Good mix – I used one for an email campaign and got 15% more opens. Definitely worth the money.' },
    { name: 'Sana K.', rating: 5, comment: 'Every hook is a gem. My posts are getting 3x comments now – I’m so happy with my purchase.' },
    { name: 'Amit D.', rating: 4, comment: 'Nice pack – could include more niche-specific hooks, but still useful. I’ll combine with other packs for best results.' },
    { name: 'Pooja B.', rating: 5, comment: 'This pack is a lifesaver – I’ve saved hours every week. Highly recommend to anyone who runs a social media account.' },
    { name: 'Gaurav L.', rating: 5, comment: 'Brilliant – fresh and engaging hooks that actually stop the scroll. My content has never been better.' },
    { name: 'Shruti M.', rating: 4, comment: 'Good resource. Would love a larger pack with more variety – but for the price, it’s a steal.' },
    { name: 'Varun C.', rating: 5, comment: 'I used one hook and got 200+ likes. This works! I’m already planning to buy the bigger bundle.' },
    { name: 'Aisha R.', rating: 5, comment: 'Perfect for someone who struggles with writer’s block – a real time‑saver. I’ve recommended it to my entire team.' },
    { name: 'Manish T.', rating: 3, comment: 'Some hooks are okay, but I expected more creativity. Still decent for beginners.' },
    { name: 'Komal W.', rating: 5, comment: 'Total game changer. My engagement stats are proof – I’ve seen a 25% increase in reach.' },
    { name: 'Harish N.', rating: 5, comment: 'Worth every paisa. Already bought the 15-pack too – this is a must-have for content creators.' },
    { name: 'Swati S.', rating: 4, comment: 'Very useful – will combine with other packs for best results. The TXT format makes it easy to edit.' },
    { name: 'Ravi P.', rating: 5, comment: 'These captions are pure gold. My DMs are full of compliments – my followers love the content.' },
    { name: 'Tanya M.', rating: 5, comment: 'I’ve been using these hooks for all my clients – they love them. It’s like having a professional copywriter in my pocket.' },
    { name: 'Siddharth B.', rating: 4, comment: 'A few hooks are repetitive, but overall a solid pack. Good value for money.' },
    { name: 'Leela N.', rating: 5, comment: 'I’m a social media manager and this pack is my go‑to – saves me so much time. Highly recommend.' },
  ],
  'ai-prompts-15': [
    { name: 'Vikram J.', rating: 5, comment: 'These prompts saved me from writer’s block – I’ve used them for 5 blog posts already. They’re well‑structured and generate great outputs.' },
    { name: 'Neha D.', rating: 4, comment: 'Good variety – some prompts are brilliant, others are average. I’d recommend it for brainstorming.' },
    { name: 'Suresh G.', rating: 5, comment: 'My team uses these daily. They’ve cut our content planning time in half – absolutely essential for our workflow.' },
    { name: 'Maya P.', rating: 5, comment: 'Super creative – I used one prompt to write a full email sequence and got a 20% open rate. Amazing.' },
    { name: 'Arjun R.', rating: 3, comment: 'Useful, but a few prompts felt too generic for my niche (real estate). Still, a good starting point.' },
    { name: 'Kavya N.', rating: 5, comment: 'I used one prompt for a blog post and it got 1000+ views in 2 days – the topic was exactly what my audience wanted.' },
    { name: 'Deepak S.', rating: 5, comment: 'This pack is a goldmine for content creators. I’ve recommended it to all my friends – they all love it.' },
    { name: 'Sneha R.', rating: 4, comment: 'Great brainstorming tool – some prompts are absolute gems. I’d love more examples in each prompt.' },
    { name: 'Ajay K.', rating: 5, comment: 'Saved me days of work. Very impressed with the quality – I’ve already used 10 of the prompts for my social media strategy.' },
    { name: 'Ritu G.', rating: 5, comment: 'I’ve been using these for my YouTube scripts – they’re fantastic. My video ideas are more creative now.' },
    { name: 'Vivek P.', rating: 2, comment: 'Too many generic prompts. Only a few were usable for my business – I expected more advanced options.' },
    { name: 'Ankit M.', rating: 4, comment: 'Worth the price – works perfectly with ChatGPT. I use them daily for my content agency.' },
    { name: 'Riya T.', rating: 5, comment: 'My content calendar is full for the next month thanks to these prompts. I’m so grateful for this pack.' },
    { name: 'Karan S.', rating: 5, comment: 'Perfect for a beginner – easy to understand and immediately useful. I’ve already created 3 pieces of content.' },
    { name: 'Meera J.', rating: 4, comment: 'Good starting point – I modify some to make them more specific to my brand. Overall, a solid purchase.' },
    { name: 'Aditya R.', rating: 5, comment: 'I run a marketing agency and these are a lifesaver – my team loves them. They’ve doubled our output.' },
    { name: 'Nisha P.', rating: 5, comment: 'Incredible value – I’ll definitely buy the larger pack. The prompts are practical and easy to adapt.' },
    { name: 'Rohit G.', rating: 3, comment: 'Some prompts are great, others are too niche for me. But for the price, it’s okay.' },
    { name: 'Sana K.', rating: 5, comment: 'These prompts sparked 10 new ideas for my business – amazing. I’ve already used 4 of them.' },
    { name: 'Amit D.', rating: 5, comment: 'I use them daily for social media posts and emails – they’re perfect. My engagement has increased significantly.' },
    { name: 'Pooja B.', rating: 4, comment: 'Good set – could include more e‑commerce focused prompts, but still very useful.' },
    { name: 'Gaurav L.', rating: 5, comment: 'Best investment for my content team this year – we’ve doubled our output. The prompts are high-quality.' },
    { name: 'Shruti M.', rating: 5, comment: 'The prompts are very detailed and actionable – no fluff. I’ve used them for multiple projects.' },
    { name: 'Varun C.', rating: 4, comment: 'I’d love more examples in each prompt – but overall solid. I’m happy with my purchase.' },
    { name: 'Aisha R.', rating: 5, comment: 'My copywriting has improved significantly. These prompts challenge me and help me think outside the box.' },
    { name: 'Manish T.', rating: 5, comment: 'Great for brainstorming new campaigns – already used three prompts for my marketing campaigns.' },
    { name: 'Komal W.', rating: 3, comment: 'Some prompts are repetitive – but there are a few standouts. I’ll stick to the ones that work.' },
    { name: 'Harish N.', rating: 5, comment: 'I’ve already made my money back with just one client – these prompts are pure gold.' },
    { name: 'Swati S.', rating: 5, comment: 'Love the diversity of topics – very practical and easy to adapt. I use them every week.' },
    { name: 'Ravi P.', rating: 4, comment: 'Good product – I combined prompts for even better results. Worth the money.' },
    { name: 'Tanya M.', rating: 5, comment: 'This pack is a must‑have for any marketer – it’s saved me so much time and effort.' },
    { name: 'Siddharth B.', rating: 5, comment: 'The prompts are well-crafted and immediately usable. I’ve recommended this to all my colleagues.' },
    { name: 'Leela N.', rating: 4, comment: 'Great for content ideation – I use them every week. A few prompts are too basic, but overall good.' },
    { name: 'Priya S.', rating: 5, comment: 'I used two prompts to create an entire campaign – it was a huge success. Highly recommend.' },
    { name: 'Rahul K.', rating: 5, comment: 'These prompts are a time‑saver, pure gold. My productivity has increased dramatically.' },
  ],
  'content-kit-50': [
    { name: 'Maya P.', rating: 5, comment: 'This kit is a goldmine for social media managers. I’ve used it for 3 different brands – it’s versatile and comprehensive.' },
    { name: 'Arjun R.', rating: 4, comment: 'Great value – the prompts are super practical, but I expected more captions. Still, a solid kit.' },
    { name: 'Kavya N.', rating: 5, comment: 'Loved the bonus resources – especially the hashtag list. My reach has improved since using them.' },
    { name: 'Deepak S.', rating: 5, comment: 'This kit has everything I need for a month of content. Perfect for busy creators like me.' },
    { name: 'Sneha R.', rating: 5, comment: 'The captions are my favourite – so creative and easy to customize. I’ve already used 5 of them.' },
    { name: 'Ajay K.', rating: 4, comment: 'Very comprehensive – a few prompts need better wording, but overall great. I’ll definitely use this often.' },
    { name: 'Ritu G.', rating: 5, comment: 'Used this kit for 3 different clients – it’s versatile and saves me hours. Highly recommend.' },
    { name: 'Vivek P.', rating: 5, comment: 'The bonus checklist is a game changer for planning my content calendar. I’m much more organised now.' },
    { name: 'Ankit M.', rating: 3, comment: 'Good mix, but I wish there were more examples for each prompt. Still, it’s helpful.' },
    { name: 'Riya T.', rating: 5, comment: 'This kit saved me so much time – I highly recommend it. The resources are well-organised.' },
    { name: 'Karan S.', rating: 5, comment: 'Perfect for a beginner like me – very easy to use and understand. I’ve already created content for a week.' },
    { name: 'Meera J.', rating: 4, comment: 'Some prompts are too basic – but the bonus resources are excellent. I’d buy again for the hashtag list alone.' },
    { name: 'Aditya R.', rating: 5, comment: 'The hashtag list alone is worth the price – my reach has grown by 30%. Amazing kit.' },
    { name: 'Nisha P.', rating: 5, comment: 'Used this kit to launch two new campaigns – both performed well. The prompts are very actionable.' },
    { name: 'Rohit G.', rating: 3, comment: 'Good, but I expected more captions – only 10? Seems low. I’ll look for a larger pack next time.' },
    { name: 'Sana K.', rating: 5, comment: 'This kit is my go‑to for content ideas – never run out now. I’ve already used 20 prompts.' },
    { name: 'Amit D.', rating: 5, comment: 'Love the variety of topics – covers everything I need. The bonus resources are a plus.' },
    { name: 'Pooja B.', rating: 4, comment: 'Solid kit – will recommend to my team for sure. A few prompts could be more detailed.' },
    { name: 'Gaurav L.', rating: 5, comment: 'One of the best content kits I’ve ever purchased – well organised and practical.' },
    { name: 'Shruti M.', rating: 5, comment: 'The bonus resources were a pleasant surprise – very useful. I’ve already used the checklist.' },
    { name: 'Varun C.', rating: 2, comment: 'Too generic for my niche – only a few prompts were usable. Disappointed with the content.' },
    { name: 'Aisha R.', rating: 5, comment: 'I’ve doubled my content output with this kit – amazing value. I’m so glad I bought it.' },
    { name: 'Manish T.', rating: 5, comment: 'Excellent value for money – I’ll definitely buy the larger pack. The prompts are very effective.' },
    { name: 'Komal W.', rating: 4, comment: 'Good kit, but I wish there were more templates included. Still, it’s a great resource.' },
    { name: 'Harish N.', rating: 5, comment: 'This kit is a lifesaver for busy marketers – I use it weekly. My content is much better now.' },
    { name: 'Swati S.', rating: 5, comment: 'I’ve recommended this to all my colleagues – everyone loves it. The captions are particularly good.' },
    { name: 'Ravi P.', rating: 5, comment: 'A complete content solution in one download – fantastic. I’m very satisfied with my purchase.' },
    { name: 'Tanya M.', rating: 4, comment: 'Very helpful, especially the caption hooks – they’re engaging. I’d love more templates.' },
    { name: 'Siddharth B.', rating: 5, comment: 'I’ve never seen such a comprehensive kit at this price – outstanding. The quality is top-notch.' },
    { name: 'Leela N.', rating: 5, comment: 'Perfect for Instagram and LinkedIn – covers all my needs. I use it every day.' },
    { name: 'Priya S.', rating: 5, comment: 'I use this kit daily – it’s become my content bible. The prompts are brilliant.' },
    { name: 'Rahul K.', rating: 4, comment: 'The prompts are excellent, the captions could use more variety. But overall, a great kit.' },
  ],
  'pro-toolkit-130': [
    { name: 'Deepak S.', rating: 5, comment: 'This toolkit is a game‑changer for my agency – we’ve streamlined everything. The strategies are pure gold.' },
    { name: 'Sneha R.', rating: 4, comment: 'Very comprehensive – but I’d like more advanced prompts for experts. Still, it’s a great toolkit.' },
    { name: 'Ajay K.', rating: 5, comment: 'Worth every penny – the strategies are pure gold and immediately actionable. My team loves it.' },
    { name: 'Ritu G.', rating: 5, comment: 'I’ve used this toolkit to grow my business by 40% in 3 months. The insights are invaluable.' },
    { name: 'Vivek P.', rating: 5, comment: 'The best investment for any serious marketer – I can’t imagine my work without it. Highly recommend.' },
    { name: 'Ankit M.', rating: 3, comment: 'Good content, but some prompts are similar to the smaller pack – still useful. I’d expect more for the price.' },
    { name: 'Riya T.', rating: 5, comment: 'This toolkit saved me months of trial and error – absolutely essential. I’ve already recommended it to my network.' },
    { name: 'Karan S.', rating: 5, comment: 'I’m an agency owner – this is exactly what I needed to scale. The strategies are practical and effective.' },
    { name: 'Meera J.', rating: 5, comment: 'The strategies section alone is worth the price – brilliant insights. I’ve already implemented 3 of them.' },
    { name: 'Aditya R.', rating: 4, comment: 'Very useful, but I expected more advanced prompts – still great. The toolkit is well-organised.' },
    { name: 'Nisha P.', rating: 5, comment: 'I’ve doubled my lead generation since using this – outstanding. The prompts are very effective.' },
    { name: 'Rohit G.', rating: 5, comment: 'My team loves the clarity and structure – we’re more productive than ever. This toolkit is a gem.' },
    { name: 'Sana K.', rating: 5, comment: 'One of the most comprehensive toolkits I’ve seen – highly recommend. The strategies are actionable.' },
    { name: 'Amit D.', rating: 4, comment: 'Good mix of strategy and execution prompts – but I wish there were more B2B examples. Still, very useful.' },
    { name: 'Pooja B.', rating: 5, comment: 'I’ve recommended this to all my business partners – it’s that good. The toolkit has transformed our workflow.' },
    { name: 'Gaurav L.', rating: 5, comment: 'The ROI from this toolkit is off the charts – my sales have increased. The prompts are pure gold.' },
    { name: 'Shruti M.', rating: 5, comment: 'Every marketer should have this in their arsenal – it’s a complete system. I use it daily.' },
    { name: 'Varun C.', rating: 4, comment: 'Great toolkit, but I wish there were more email marketing prompts. Still, it’s a solid investment.' },
    { name: 'Aisha R.', rating: 5, comment: 'This has become my go‑to resource for client work – pure gold. My clients are thrilled with the results.' },
    { name: 'Manish T.', rating: 5, comment: 'The captions are brilliant – my engagement skyrocketed. I’ve already used 20 of the prompts.' },
    { name: 'Komal W.', rating: 5, comment: 'Worth every rupee – I’ve bought other packs but this is the best. The strategies are exceptional.' },
    { name: 'Harish N.', rating: 4, comment: 'Very comprehensive – a few prompts need better targeting for my niche. But overall, excellent.' },
    { name: 'Swati S.', rating: 5, comment: 'I use this toolkit daily to manage multiple client accounts – it’s a lifesaver. Highly recommend.' },
    { name: 'Ravi P.', rating: 5, comment: 'This toolkit is pure gold for anyone in digital marketing – I’ve already made 5x my investment.' },
    { name: 'Tanya M.', rating: 5, comment: 'The structure of the prompts is amazing – very actionable and clear. I’ve improved my strategies significantly.' },
    { name: 'Siddharth B.', rating: 4, comment: 'Good variety, but some prompts are repetitive – still a solid toolkit. I’d recommend it.' },
    { name: 'Leela N.', rating: 5, comment: 'This toolkit has transformed my content workflow – I’m now 2x faster. The strategies are excellent.' },
    { name: 'Suresh G.', rating: 5, comment: 'I’ve already made 5x my investment using these prompts – incredible. This is a must‑have.' },
    { name: 'Vikram J.', rating: 5, comment: 'An absolute must‑have for any marketing team – I use it daily. The quality is exceptional.' },
    { name: 'Neha D.', rating: 5, comment: 'I’ve been recommending this to everyone in my network – it’s fantastic. The toolkit is a game‑changer.' },
  ],
  'ultimate-ai-bundle-400': [
    { name: 'Ankit M.', rating: 5, comment: 'This bundle has everything – I use it daily and it’s never let me down. The variety is incredible.' },
    { name: 'Ritu G.', rating: 5, comment: 'Insane value for money – 400 resources at this price is unheard of. I’m blown away by the quality.' },
    { name: 'Vivek P.', rating: 4, comment: 'Great variety – some prompts are truly innovative, but a few are duplicates. Still, it’s a fantastic bundle.' },
    { name: 'Riya T.', rating: 5, comment: 'This is the ultimate resource library – I’m blown away by the depth. I’ve used it for multiple projects.' },
    { name: 'Karan S.', rating: 5, comment: 'I’ve stopped using other tools – this bundle covers everything I need. It’s a complete ecosystem.' },
    { name: 'Meera J.', rating: 5, comment: 'The case studies are incredibly insightful – I’ve learned so much. This bundle is a game‑changer.' },
    { name: 'Aditya R.', rating: 5, comment: 'Best purchase of my career – absolutely recommended. The resources are top-notch.' },
    { name: 'Nisha P.', rating: 4, comment: 'Very comprehensive, but a few prompts are duplicates – still excellent value. I’d buy it again.' },
    { name: 'Rohit G.', rating: 5, comment: 'This bundle is a goldmine for any content creator – I’ve used it for 10 projects. Highly recommend.' },
    { name: 'Sana K.', rating: 5, comment: 'I’ve already shared this with my entire team – they all love it. The bundle is incredibly useful.' },
    { name: 'Amit D.', rating: 5, comment: 'Unbelievable value – the prompts are top‑notch and cover every niche. I’m very satisfied.' },
    { name: 'Pooja B.', rating: 5, comment: 'I’ve been using this bundle for a month and my output has doubled. It’s been a huge help.' },
    { name: 'Gaurav L.', rating: 5, comment: 'Hands down the best digital product I’ve ever bought – period. The resources are exceptional.' },
    { name: 'Shruti M.', rating: 4, comment: 'Great bundle – I wish there were more social media templates. Still, it’s a fantastic collection.' },
    { name: 'Varun C.', rating: 5, comment: 'The captions are fantastic – very engaging and easy to adapt. I’ve used them for multiple clients.' },
    { name: 'Aisha R.', rating: 5, comment: 'I’ve recommended this to all my freelancer friends – it’s a game‑changer. The bundle is outstanding.' },
    { name: 'Manish T.', rating: 5, comment: 'This bundle is a productivity powerhouse – I’ve never worked faster. The prompts are excellent.' },
    { name: 'Komal W.', rating: 5, comment: 'Worth every rupee – I’ll definitely be buying future bundles too. The quality is consistent.' },
    { name: 'Harish N.', rating: 5, comment: 'The prompt variety is incredible – covers every niche I can think of. I’m very impressed.' },
    { name: 'Swati S.', rating: 5, comment: 'I’ve never seen such a comprehensive bundle anywhere – stunning. It’s a must‑have.' },
    { name: 'Ravi P.', rating: 4, comment: 'Excellent, but I could do without the duplicate prompts – still fantastic. I’d recommend it.' },
    { name: 'Tanya M.', rating: 5, comment: 'My content quality has improved dramatically – I’m more confident now. This bundle is amazing.' },
    { name: 'Siddharth B.', rating: 5, comment: 'A must‑have for any serious creator or marketer – I use it daily. The resources are top-notch.' },
    { name: 'Leela N.', rating: 5, comment: 'I use this bundle every single day without fail – it’s my backbone. Highly recommend.' },
    { name: 'Suresh G.', rating: 5, comment: 'The ROI is incredible – I’ve already landed new clients using these prompts. This bundle is gold.' },
    { name: 'Vikram J.', rating: 5, comment: 'This bundle is the best investment I’ve made this year – hands down. The quality is exceptional.' },
    { name: 'Neha D.', rating: 5, comment: 'The captions alone are worth the price – amazing bundle! I’m so glad I bought it.' },
    { name: 'Deepak S.', rating: 5, comment: 'Every creative should own this bundle – it’s pure gold. The resources are incredible.' },
    { name: 'Sneha R.', rating: 5, comment: 'I’ve been blown away by the depth and quality – highly recommended. This bundle is a masterpiece.' },
    { name: 'Ajay K.', rating: 5, comment: 'The ultimate package – I’ll never need to search for resources again. It’s everything I need.' },
  ],
  'elite-creator-suite': [
    { name: 'Aisha R.', rating: 5, comment: 'This suite is absolutely incredible – I’ve stopped using any other tools. It’s the ultimate resource.' },
    { name: 'Vikram S.', rating: 5, comment: 'Worth every rupee – the masterclass alone is a game changer. I’ve already implemented the strategies.' },
    { name: 'Meera J.', rating: 5, comment: 'I’ve been using this for two weeks and my productivity has skyrocketed. The suite is amazing.' },
    { name: 'Rahul K.', rating: 5, comment: 'The Canva templates are stunning – I’ve already used them for 5 clients. They’re professional and easy to edit.' },
    { name: 'Ananya M.', rating: 4, comment: 'Amazing value – the only downside is that it’s a large download. But the content is worth it.' },
    { name: 'Deepak S.', rating: 5, comment: 'The prompts are diverse and high quality – covers every niche imaginable. I’m very impressed.' },
    { name: 'Priya S.', rating: 5, comment: 'I was hesitant at first, but this suite paid for itself within a week. The resources are excellent.' },
    { name: 'Suresh G.', rating: 5, comment: 'Lifetime updates is a huge bonus – I’m excited for future additions. This suite is a great investment.' },
    { name: 'Kavya N.', rating: 5, comment: 'The marketing frameworks helped me restructure my entire strategy – brilliant. I’m seeing better results.' },
    { name: 'Arjun R.', rating: 4, comment: 'Very comprehensive – just wish there were more video tutorials. Still, it’s a fantastic suite.' },
    { name: 'Neha D.', rating: 5, comment: 'This suite is a complete ecosystem for creators – I love it. It’s saved me so much time.' },
    { name: 'Ajay K.', rating: 5, comment: 'My agency has grown 3x since I started using these resources. The suite is a game‑changer.' },
    { name: 'Ritu G.', rating: 5, comment: 'The captions are clever and original – my engagement has doubled. This suite is excellent.' },
    { name: 'Vivek P.', rating: 5, comment: 'One of the best investments I’ve made for my business. The suite is comprehensive and well-organised.' },
    { name: 'Ankit M.', rating: 5, comment: 'I love the variety – there’s something for every platform. The suite is incredibly useful.' },
    { name: 'Riya T.', rating: 5, comment: 'The commercial license is a huge plus for freelancers – I feel safe using this. It’s a great investment.' },
    { name: 'Karan S.', rating: 4, comment: 'Great product – I’d love even more email templates. But overall, it’s a solid suite.' },
    { name: 'Maya P.', rating: 5, comment: 'This suite has replaced 10 different subscriptions for me – huge savings. The content is top-notch.' },
    { name: 'Sneha R.', rating: 5, comment: 'The masterclass video is worth the price alone – so insightful. I’ve learned a lot from it.' },
    { name: 'Gaurav L.', rating: 5, comment: 'I’ve recommended this to all my colleagues – it’s that good. The suite is a must‑have.' },
    { name: 'Shruti M.', rating: 5, comment: 'The resources are top‑notch and the updates keep coming – excellent. I’m very satisfied.' },
    { name: 'Varun C.', rating: 4, comment: 'Excellent, but I wish there were more Instagram story templates. Still, it’s a great suite.' },
    { name: 'Komal W.', rating: 5, comment: 'This suite is a lifesaver – my content calendar is full for months. I’m so happy with my purchase.' },
    { name: 'Harish N.', rating: 5, comment: 'I’ve used prompts from this suite to land three new clients – unbelievable. The suite is incredible.' },
    { name: 'Swati S.', rating: 5, comment: 'The quality is consistent – every file is well‑organized and usable. The suite is excellent.' },
    { name: 'Ravi P.', rating: 5, comment: 'I’ve saved hundreds of hours with these templates and prompts. The suite is a huge time‑saver.' },
    { name: 'Tanya M.', rating: 5, comment: 'An absolute must‑have for any serious content creator – I can’t live without it. The suite is amazing.' },
    { name: 'Siddharth B.', rating: 5, comment: 'The variety is overwhelming – in a good way! Everything is useful. The suite is a goldmine.' },
    { name: 'Leela N.', rating: 5, comment: 'I use this suite daily and it has simplified my workflow immensely. The suite is fantastic.' },
    { name: 'Manish T.', rating: 5, comment: 'I’ve already made back my investment ten times over – incredible value. The suite is a game‑changer.' },
  ],
  'ai-ultimate-collection-2026': [
    { name: 'Arjun M.', rating: 5, comment: 'This collection is incredible – 200+ prompts that actually work! I’ve already used 20 of them for my content. My productivity has gone through the roof.' },
    { name: 'Priya R.', rating: 5, comment: 'The templates saved me hours of design work – my social media looks professional now. I’ve already used 5 of them.' },
    { name: 'Vikram S.', rating: 4, comment: 'Great value for money – the trend guide alone is worth it. I’ve already started implementing the strategies.' },
    { name: 'Neha K.', rating: 5, comment: 'I’ve been using these prompts for my agency – clients are thrilled with the results. The collection is a lifesaver.' },
    { name: 'Suresh G.', rating: 5, comment: 'The commercial license is a game‑changer for freelancers – I can now pitch to bigger clients. I’m very happy with this purchase.' },
    { name: 'Ananya M.', rating: 5, comment: 'This collection covers everything I need for content creation – perfect. I’ve already used it for multiple projects.' },
    { name: 'Rahul D.', rating: 4, comment: 'Some prompts are similar, but overall a solid pack – great starting point. I’d recommend it to others.' },
    { name: 'Maya P.', rating: 5, comment: 'Best investment for my business this year – I’ve already seen results. The collection is excellent.' },
    { name: 'Deepak S.', rating: 5, comment: 'Lifetime updates – that’s what made me buy it. Future‑proof. I’m excited to see what’s added next.' },
    { name: 'Kavya N.', rating: 5, comment: 'The Canva templates are stunning – my brand finally looks cohesive. The collection is a game‑changer.' },
    { name: 'Ajay K.', rating: 4, comment: 'Very comprehensive – I wish there were more video tutorials included. Still, it’s a great collection.' },
    { name: 'Ritu G.', rating: 5, comment: 'I’ve already recommended this to my entire team – we’re all using it. The collection is amazing.' },
    { name: 'Vivek P.', rating: 5, comment: 'The prompts are diverse and high‑quality – I’ve used them for 5 different niches. The collection is versatile.' },
    { name: 'Ankit M.', rating: 5, comment: 'I use this collection daily – it’s my go‑to resource for everything. It’s been a huge help.' },
    { name: 'Riya T.', rating: 5, comment: 'Absolutely worth every rupee – my content output has doubled. The collection is a lifesaver.' },
    { name: 'Karan S.', rating: 4, comment: 'Great collection, but I’d like more templates for Instagram stories. Still, it’s a solid buy.' },
    { name: 'Meera J.', rating: 5, comment: 'The trend guide helped me pivot my strategy – brilliant insights. The collection is well-curated.' },
    { name: 'Aditya R.', rating: 5, comment: 'Best ₹299 I’ve ever spent – the ROI is incredible. I’ve already made back my money.' },
    { name: 'Nisha P.', rating: 5, comment: 'I’ve been using this for two weeks and my engagement is up 40%. The collection is pure gold.' },
    { name: 'Rohit G.', rating: 5, comment: 'The prompts are well‑structured and easy to adapt – I love them. The collection is very practical.' },
    { name: 'Sana K.', rating: 5, comment: 'This collection is a goldmine for creators – I’ve found 10 new ideas already. I’m very satisfied.' },
    { name: 'Amit D.', rating: 4, comment: 'Good variety – could include more B2B prompts, but still excellent. I’d recommend it.' },
    { name: 'Pooja B.', rating: 5, comment: 'I’ve saved hours of work – highly recommend to anyone serious about AI. The collection is top-tier.' },
    { name: 'Gaurav L.', rating: 5, comment: 'The templates are top‑notch – my clients love the new designs. The collection is a game‑changer.' },
    { name: 'Shruti M.', rating: 5, comment: 'The lifetime updates give me peace of mind – I’m set for the future. The collection is a great investment.' },
    { name: 'Varun C.', rating: 4, comment: 'Excellent, but the file size is a bit large – still worth it though. The collection is comprehensive.' },
    { name: 'Aisha R.', rating: 5, comment: 'This collection has everything a creator needs – I’m so happy with it. It’s been a huge help.' },
    { name: 'Manish T.', rating: 5, comment: 'I’ve already created 10+ campaigns using these resources – incredible. The collection is fantastic.' },
    { name: 'Komal W.', rating: 5, comment: 'The value is unbeatable – I’m a loyal customer now. The collection is top-quality.' },
    { name: 'Harish N.', rating: 5, comment: 'I’ve recommended this to all my freelancer friends – they all love it. The collection is pure gold.' },
    { name: 'Swati S.', rating: 5, comment: 'The prompts are creative and produce great outputs – my team loves them. The collection is excellent.' },
    { name: 'Ravi P.', rating: 5, comment: 'I’ve tripled my content output using this collection – thank you! It’s been a game‑changer.' },
    { name: 'Tanya M.', rating: 5, comment: 'A must‑have for any serious marketer – you won’t regret it. The collection is amazing.' },
    { name: 'Siddharth B.', rating: 5, comment: 'The variety is amazing – something for every platform and niche. The collection is incredibly useful.' },
    { name: 'Leela N.', rating: 5, comment: 'I use it every day – it’s become essential to my workflow. The collection is a lifesaver.' },
  ],
};